[build]

  command = "CI= npm run build"
  publish="/build"
  base="/"

  command = "CI= npm add bootstrap react-bootstrap"
  publish="/build"
  base="/"

[[redirects]]
  from ="/*"
  to="/index.html"
  status=200